import pandas as pd
import numpy as np
import os
from matplotlib import pyplot as plt

# get the Path of current file
Path = os.path.dirname(os.path.abspath(__file__))
# print(Path)

list_of_errors_csv = os.listdir(Path + '/cov_per_error/')
print('list_of_errors_csv ', len(list_of_errors_csv))

# get the error csv file and sum them up and save as a new csv file
# read the csv file
columns = ['nn', 'ee', 'vv', 'ne', 'nv', 'ev']
# make a empty pandas dataframe with columns
sum_of_errors = pd.DataFrame(columns=columns)
for file in list_of_errors_csv:
    # print file name
    # print(file)
    # read the csv file
    df = pd.read_csv(Path + '/cov_per_error/' + file)
    # sum up row by row to get the total error just for columns nn, ee, vv, ne, nv, ev
    sum_of_errors = sum_of_errors.add(df[columns], fill_value=0)
# print(sum_of_errors)
# save the sum of errors to csv file
sum_of_errors.to_csv(Path + '/AA_sum_of_errors.csv', index=False)

# read excel file
ISCWSA_file_name = 'error-model-example-mwdrev5-1-iscwsa-1.xlsx'
df = pd.read_excel(ISCWSA_file_name)

for tab in list_of_errors_csv:
    tab = tab.replace('.csv', '')

    ISCWSA_cov_nev = pd.read_excel(
        ISCWSA_file_name,
        sheet_name=tab,
        usecols="Q:V",
        header=1
        )

    # drop the last row of ISCWSA_cov_nev
    ISCWSA_cov_nev.drop(ISCWSA_cov_nev.tail(1).index, inplace=True)
    # check if in the column name there is string 1 if so remove it
    ISCWSA_cov_nev.columns = [col.replace('.1', '') for col in ISCWSA_cov_nev.columns]

    # read the data generated by the corva-welleng for each error
    corva_welleng_cov_nev = pd.read_csv(Path + '/cov_per_error/' + tab + '.csv')
    # drop the first column of corva_welleng_cov_nev
    corva_welleng_cov_nev.drop(corva_welleng_cov_nev.columns[0], axis=1, inplace=True)
    # rename the columns of corva_welleng_cov_nev
    corva_welleng_cov_nev.columns = ['NN', 'EE', 'VV', 'NE', 'NV', 'EV']

    # compute the error between ISCWSA_cov_nev and corva_welleng_cov_nev for each column
    diff = ISCWSA_cov_nev - corva_welleng_cov_nev
    error = diff / ISCWSA_cov_nev
    # calculate error percentage
    error_percentage = error * 100

    # print the shape of error_percentage for each tab
    print(tab, error_percentage.shape)
    if tab == "XCLA":
        print(tab)
        print("")

    # a depth column for plotting the error
    # between 0 and 8000 increment by 30
    depth = np.arange(0, 8030, 30)

    # plot scatter the error percentage for each column in one plot
    fig, ax = plt.subplots()
    ax.scatter(depth, error_percentage['NN'], label='NN')
    ax.scatter(depth, error_percentage['EE'], label='EE')
    ax.scatter(depth, error_percentage['VV'], label='VV')
    ax.scatter(depth, error_percentage['NE'], label='NE')
    ax.scatter(depth, error_percentage['NV'], label='NV')
    ax.scatter(depth, error_percentage['EV'], label='EV')
    ax.set_xlabel('Depth (m)')
    ax.set_ylabel('Error (%)')
    ax.set_title(tab)
    ax.legend()
    plt.show()


