import pandas as pd
import numpy as np
import os
from matplotlib import pyplot as plt
import warnings

warnings.filterwarnings("ignore")
# get the Path of current file
Path = os.path.dirname(os.path.abspath(__file__))
# print(Path)

list_of_errors_csv = os.listdir(Path + '/cov_per_error/')
print('list_of_errors_csv ', len(list_of_errors_csv))

# get the error csv file and sum them up and save as a new csv file
# read the csv file
columns = ['nn', 'ee', 'vv', 'ne', 'nv', 'ev']
# make a empty pandas dataframe with columns
sum_of_errors = pd.DataFrame(columns=columns)
for file in list_of_errors_csv:
    # print file name
    # print(file)
    # read the csv file
    df = pd.read_csv(Path + '/cov_per_error/' + file)
    # sum up row by row to get the total error just for columns nn, ee, vv, ne, nv, ev
    sum_of_errors = sum_of_errors.add(df[columns], fill_value=0)
# print(sum_of_errors)
# save the sum of errors to csv file
sum_of_errors.to_csv(Path + '/AA_sum_of_errors.csv', index=False)

# read excel file
ISCWSA_file_name = 'error-model-example-mwdrev5-1-iscwsa-1.xlsx'
df = pd.read_excel(ISCWSA_file_name)

jump = True
for tab in list_of_errors_csv:
    if jump:
        continue
    tab = tab.replace('.csv', '')

    ISCWSA_cov_nev = pd.read_excel(
        ISCWSA_file_name,
        sheet_name=tab,
        usecols="Q:V",
        header=1
    )

    # drop the last row of ISCWSA_cov_nev
    ISCWSA_cov_nev.drop(ISCWSA_cov_nev.tail(1).index, inplace=True)
    # check if in the column name there is string 1 if so remove it
    ISCWSA_cov_nev.columns = [col.replace('.1', '') for col in ISCWSA_cov_nev.columns]

    # read the data generated by the corva-welleng for each error
    corva_welleng_cov_nev = pd.read_csv(Path + '/cov_per_error/' + tab + '.csv')
    # drop the first column of corva_welleng_cov_nev
    corva_welleng_cov_nev.drop(corva_welleng_cov_nev.columns[0], axis=1, inplace=True)
    # rename the columns of corva_welleng_cov_nev
    corva_welleng_cov_nev.columns = ['NN', 'EE', 'VV', 'NE', 'NV', 'EV']

    # compute the error between ISCWSA_cov_nev and corva_welleng_cov_nev for each column
    diff = corva_welleng_cov_nev - ISCWSA_cov_nev
    error = diff / ISCWSA_cov_nev
    # calculate error percentage
    error_percentage = error * 100

    # print the shape of error_percentage for each tab
    print(tab, error_percentage.shape)
    # if tab == "XCLA":
    #     print(tab)
    #     print("")

    # a depth column for plotting the error
    # between 0 and 8000 increment by 30
    depth = np.arange(0, 8030, 30)

    # plot scatter the error percentage for each column in one plot
    fig, ax = plt.subplots()
    ax.scatter(depth, error_percentage['NN'], label='NN')
    ax.scatter(depth, error_percentage['EE'], label='EE')
    ax.scatter(depth, error_percentage['VV'], label='VV')
    ax.scatter(depth, error_percentage['NE'], label='NE')
    ax.scatter(depth, error_percentage['NV'], label='NV')
    ax.scatter(depth, error_percentage['EV'], label='EV')
    ax.set_xlabel('Depth (m)')
    ax.set_ylabel('Error (%)')
    ax.set_title(tab)
    ax.legend()
    # save the plot in error figues folder
    plt.savefig(Path + '/error_figures/' + tab + '.png')
    # plt.show()

# print(sum_of_errors)

# calculate sum of errors percentage and plot
Calculate_sum_err = True
if Calculate_sum_err:
    ISCWSA_TOTAL_cov_nev = pd.read_excel(
        ISCWSA_file_name,
        sheet_name='TOTALS',
        usecols="B:G",
        header=1
    )

    # print(ISCWSA_TOTAL_cov_nev.shape)

    # compute the error between ISCWSA_cov_nev and corva_welleng_cov_nev for each column
    sum_of_errors.columns = ['NN', 'EE', 'VV', 'NE', 'NV', 'EV']
    diff = sum_of_errors - ISCWSA_TOTAL_cov_nev
    # change the type of diff to float
    diff = diff.astype(float)
    error = diff / ISCWSA_TOTAL_cov_nev
    depth = np.arange(0, 8030, 30)
    # calculate error percentage
    error_percentage = error * 100
    error_percentage.columns = ['NN', 'EE', 'VV', 'NE', 'NV', 'EV']
    # plot scatter the error percentage for each column in one plot
    fig, ax = plt.subplots()
    ax.scatter(depth, error_percentage['NN'], label='NN')
    ax.scatter(depth, error_percentage['EE'], label='EE')
    ax.scatter(depth, error_percentage['VV'], label='VV')
    ax.scatter(depth, error_percentage['NE'], label='NE')
    ax.scatter(depth, error_percentage['NV'], label='NV')
    ax.scatter(depth, error_percentage['EV'], label='EV')
    ax.set_xlabel('Depth (m)')
    ax.set_ylabel('Error (%)')
    ax.set_title("TOTALS")
    ax.legend()

    # save the plot in error figues folder
    plt.savefig(Path + '/error_figures/' + "TOTALS" + '.png')
    plt.show()

# import r2_score from sklearn.metrics
from sklearn.metrics import r2_score

# plot the ISCWSA TOTALS cov NEV versus the sum of errors cov NEV
# on a 3x2 subplot
fig, axs = plt.subplots(3, 2)
fig.suptitle('Cov NEV')

columns = ['NN', 'EE', 'VV', 'NE', 'NV', 'EV']

sum_of_errors = sum_of_errors.astype(float)
ISCWSA_TOTAL_cov_nev = ISCWSA_TOTAL_cov_nev.astype(float)

# plot using loop for each column
for i in range(3):
    for j in range(2):
        axs[i, j].scatter(ISCWSA_TOTAL_cov_nev[columns[i * 2 + j]], sum_of_errors[columns[i * 2 + j]])
        axs[i, j].set_xlabel('ISCWSA TOTALS')
        axs[i, j].set_ylabel('Corva-welleng')
        axs[i, j].set_title(columns[i * 2 + j])

        # fit a line to the data
        z = np.polyfit(ISCWSA_TOTAL_cov_nev[columns[i * 2 + j]],
                       sum_of_errors[columns[i * 2 + j]], 1)
        p = np.poly1d(z)
        axs[i, j].plot(ISCWSA_TOTAL_cov_nev[columns[i * 2 + j]],
                       p(ISCWSA_TOTAL_cov_nev[columns[i * 2 + j]]), "r--")

        # show the equation of the line with 2 decimal places
        axs[i, j].text(0.05, 0.9, 'y = ' + str(round(z[0], 3)) + 'x + ' + str(round(z[1], 2)),
                       transform=axs[i, j].transAxes,
                       fontsize=8,
                       verticalalignment='top')

        # calculate the r2 score
        r2 = r2_score(ISCWSA_TOTAL_cov_nev[columns[i * 2 + j]],
                      sum_of_errors[columns[i * 2 + j]])
        axs[i, j].text(0.05, 0.7, 'r2 = ' + str(round(r2, 3)),
                       transform=axs[i, j].transAxes,
                       fontsize=8,
                       verticalalignment='top')

# make plot tight layout
plt.tight_layout()
plt.show()
