"""c0 of Eq. 15 as a QUARTIC IN u = R^2 — generated, do not hand-edit.

The critical radius is a closed-form root, not a search: c0 contains R1 and R2
only at even powers, so ``c0(R) = 0`` is a quartic in ``u = R**2``.

Coefficients are expressed in ``w = 1 - mu`` rather than ``mu``. The leading
coefficient carries ``w**2`` and vanishes as the poses approach collinear;
evaluated from ``mu`` it degenerates into cancellation noise at machine epsilon
and corrupts every root. The caller MUST pass ``w`` computed without
cancellation — for unit tangents ``1 - t1.t4 == |t1 - t4|**2 / 2``.

Generated by ``scripts/extract_eq15_c0_quartic.py``; equivalence to core's
``_eq15_coeffs(...)[0]`` is pinned by test.
"""


def eq15_c0_quartic(psi2, g1, g4, w, ratio):
    """Coefficients of c0 as a polynomial in u = R**2, LOW ORDER FIRST.

    ``c0(R) = a0 + a1*u + a2*u**2 + a3*u**3 + a4*u**4``, u = R**2,
    with ``w = 1 - mu``. All inputs broadcast (numpy or cupy).
    """
    K00 = 2*g1*g4*psi2**4 + psi2**5*w
    K02 = 16*g1*g4**3*psi2**2 - 16*g1*g4*psi2**3 + w*(8*g4**2*psi2**3 - 8*psi2**4)
    K04 = 32*g1*g4**5 - 64*g1*g4**3*psi2 + 32*g1*g4*psi2**2 + w*(16*g4**4*psi2 - 32*g4**2*psi2**2 + 16*psi2**3)
    K20 = 16*g1**3*g4*psi2**2 - 16*g1*g4*psi2**3 + w*(8*g1**2*psi2**3 - 8*psi2**4)
    K22 = -64*g1**3*g4**3 - 64*g1**3*g4*psi2 + 256*g1**2*g4**2*psi2 - 32*g1**2*psi2**2 - 64*g1*g4**3*psi2 - 32*g4**2*psi2**2 + w*(-160*g1**2*g4**2*psi2 - 32*g1**2*psi2**2 + 192*g1*g4*psi2**2 - 32*g4**2*psi2**2 + 32*psi2**3 + w*(-80*g1*g4*psi2**2 - 8*psi2**3*w + 32*psi2**3))
    K24 = 128*g1**3*g4 - 384*g1**2*g4**2 + 384*g1*g4**3 - 128*g4**4 + w*(256*g1**2*g4**2 + 64*g1**2*psi2 - 256*g1*g4**3 - 384*g1*g4*psi2 + 320*g4**2*psi2 + w*(64*g1*g4**3 + 192*g1*g4*psi2 - 128*g4**2*psi2 - 128*psi2**2 + w*(32*g4**2*psi2 + 32*psi2**2)))
    K40 = 32*g1**5*g4 - 64*g1**3*g4*psi2 + 32*g1*g4*psi2**2 + w*(16*g1**4*psi2 - 32*g1**2*psi2**2 + 16*psi2**3)
    K42 = -128*g1**4 + 384*g1**3*g4 - 384*g1**2*g4**2 + 128*g1*g4**3 + w*(-256*g1**3*g4 + 256*g1**2*g4**2 + 320*g1**2*psi2 - 384*g1*g4*psi2 + 64*g4**2*psi2 + w*(64*g1**3*g4 - 128*g1**2*psi2 + 192*g1*g4*psi2 - 128*psi2**2 + w*(32*g1**2*psi2 + 32*psi2**2)))
    K44 = w**2*(-128*g1**2 + 256*g1*g4 - 128*g4**2 + w*(-256*g1*g4 + 256*psi2 + w*(32*g1*g4 + 16*psi2*w - 128*psi2)))
    r2 = ratio ** 2
    r4 = r2 * r2
    return (
        K00,
        K20 + K02 * r2,
        K40 + K22 * r2 + K04 * r4,
        K42 * r2 + K24 * r4,
        K44 * r4,
    )
